package dam.fx3.modelo.entities;
// Generated 3 may 2024 1:08:40 by Hibernate Tools 4.3.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;


import java.io.Serial;

/**
 * Driver generated by hbm2java
 */


@Setter
@Entity
@Table(name = "driver", catalog = "fx3")
public class Driver implements java.io.Serializable {

	@Serial
	private static final long serialVersionUID = 1L;
	private int driverNumber;
	private String broadcastName;
	private String countryCode;
	private String firstName;
	private String fullName;
	private String image;
	private String lastName;
	private String teamColour;
	private String teamName;
	private String nameAcronym;

	public Driver() {
	}

	public Driver(int driverNumber) {
		this.driverNumber = driverNumber;
	}

	public Driver(int driverNumber, String broadcastName, String countryCode, String firstName, String fullName,
			String image, String lastName, String teamColour, String teamName, String nameAcronym) {
		this.driverNumber = driverNumber;
		this.broadcastName = broadcastName;
		this.countryCode = countryCode;
		this.firstName = firstName;
		this.fullName = fullName;
		this.image = image;
		this.lastName = lastName;
		this.teamColour = teamColour;
		this.teamName = teamName;
		this.nameAcronym = nameAcronym;
	}
	
	@Id
	@Column(name = "driver_number", unique = true, nullable = false)
	public int getDriverNumber() {
		return this.driverNumber;
	}

	@Column(name = "broadcast_name")
	public String getBroadcastName() {
		return this.broadcastName;
	}

	@Column(name = "country_code", length = 3)
	public String getCountryCode() {
		return this.countryCode;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	@Column(name = "team_colour", length = 10)
	public String getTeamColour() {
		return this.teamColour;
	}

	@Column(name = "team_name")
	public String getTeamName() {
		return this.teamName;
	}

	@Column(name = "name_acronym")
	public String getNameAcronym() {
		return this.nameAcronym;
	}


}
