package dam.fx3.modelo.entities;
// Generated 3 may 2024 1:08:40 by Hibernate Tools 4.3.6.Final



import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Setter;


import java.io.Serial;

/**
 * League generated by hbm2java
 */

@Setter
@Entity
@Table(name = "league", catalog = "fx3")
public class League implements java.io.Serializable {

	@Serial
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY) 
	private Integer id;
	private String name;
	private String accesscode;

	public League() {
	}

	public League(String name) {
		this.name = name;
	}

	public League(String name, String accesscode) {
		this.name = name;
		this.accesscode = accesscode;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	@Column(name = "accesscode", length = 20)
	public String getAccesscode() {
		return this.accesscode;
	}

}
