package dam.fx3.modelo.entities;
// Generated 3 may 2024 1:08:40 by Hibernate Tools 4.3.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.io.Serial;

/**
 * UserleagueId generated by hbm2java
 */

@Embeddable
public class UserleagueId implements java.io.Serializable {

	@Serial
	private static final long serialVersionUID = 1L;

	private int iduser;
	private int idleague;

	public UserleagueId() {
	}

	public UserleagueId(int iduser, int idleague) {
		this.iduser = iduser;
		this.idleague = idleague;
	}
	
	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Column(name = "idleague", nullable = false)
	public int getIdleague() {
		return this.idleague;
	}

	public void setIdleague(int idleague) {
		this.idleague = idleague;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserleagueId))
			return false;
		UserleagueId castOther = (UserleagueId) other;

		return (this.getIduser() == castOther.getIduser()) && (this.getIdleague() == castOther.getIdleague());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIduser();
		result = 37 * result + this.getIdleague();
		return result;
	}
}
