package dam.fx3.modelo.entities;
// Generated 3 may 2024 1:08:40 by Hibernate Tools 4.3.6.Final



import java.io.Serial;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * User generated by hbm2java
 */
@Data
@Entity
@Table(name = "user", catalog = "fx3")
public class User implements java.io.Serializable {

	@Serial
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "password", nullable = false, length = 64)
	private String password;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private List<Userleague> userleagues = new ArrayList<Userleague>();

}
